/**
 * commands/scaffold.mjs — via scaffold
 * Deploy a complete AI working setup to any project in one command.
 * Drops the right config files for every tool installed.
 * Wires context injection, task board, and persona.
 *
 * Usage:
 *   via scaffold                  # scaffold current directory
 *   via scaffold ./my-project
 *   via scaffold --dry-run        # preview what would be written
 */

import { existsSync, writeFileSync, mkdirSync } from 'fs';
import { join, resolve } from 'path';
import { detectTools, detectOS } from '../utils/detect.mjs';
import { green, yellow, dim, bold, blank } from '../utils/format.mjs';

const CLAUDE_MD = `# Project Context

> Generated by Via — https://github.com/Vektor-Memory/Via

## Task board
Run \`via task\` to see open tasks.

## Context injection
Run \`via context --query "project" --for claude\` to inject memory.

## Handoff
Run \`via handoff --export\` before switching tools.
`;

const CURSOR_MDC = `---
description: Via project context rules
globs: '**/*'
alwaysApply: true
---
# Via Context — Cursor Rules

Use \`via context --query "<topic>" --for cursor\` to pull project memory.
Use \`via task\` to check the shared task board.
`;

const WINDSURF_MD = `# Windsurf Context

Use \`via context --query "<topic>" --for windsurf\` to pull project memory.
`;

const VIA_CONFIG = (tools) => JSON.stringify({
  project:    true,
  tools:      Object.entries(tools).filter(([,v]) => v).map(([k]) => k),
  created_at: new Date().toISOString(),
}, null, 2);

function write(path, content, dry) {
  if (dry) {
    console.log(`  ${yellow('[dry-run]')} would write: ${path}`);
    return;
  }
  writeFileSync(path, content, 'utf8');
  console.log(`  ${green('✓')} ${path}`);
}

function ensureDir(dir, dry) {
  if (!dry && !existsSync(dir)) mkdirSync(dir, { recursive: true });
}

export async function run(args) {
  const dry    = args.includes('--dry-run') || args.includes('--dry');
  const asJSON = args.includes('--json');
  const target = args.find(a => !a.startsWith('--')) ?? '.';
  const dir    = resolve(target);

  if (!existsSync(dir)) {
    console.error(`  Directory not found: ${dir}`);
    process.exit(1);
  }

  const tools = detectTools();

  console.log(`\n  ${bold('via scaffold')}${dry ? dim(' (dry run)') : ''} → ${dir}\n`);

  const written = [];

  // .via-project.json — project marker
  const projectConfig = join(dir, '.via-project.json');
  write(projectConfig, VIA_CONFIG(tools), dry);
  written.push(projectConfig);

  // Claude: CLAUDE.md
  if (tools.claude) {
    const p = join(dir, 'CLAUDE.md');
    write(p, CLAUDE_MD, dry);
    written.push(p);
  }

  // Cursor: .cursorrules
  if (tools.cursor) {
    const p = join(dir, '.cursorrules');
    write(p, CURSOR_RULES, dry);
    written.push(p);
  }

  // Windsurf: .windsurfrules
  if (tools.windsurf) {
    const p = join(dir, '.windsurfrules');
    write(p, WINDSURF_MD, dry);
    written.push(p);
  }

  // .viaignore — tell via ingest what to skip
  const viaignore = join(dir, '.viaignore');
  write(viaignore, `node_modules\n.git\ndist\nbuild\n*.lock\n`, dry);
  written.push(viaignore);

  blank();
  if (!dry) {
    console.log(`  ${tools.claude    ? green('claude ✓') : dim('claude –')}   ${tools.cursor   ? green('cursor ✓') : dim('cursor –')}   ${tools.windsurf ? green('windsurf ✓') : dim('windsurf –')}`);
    blank();
    console.log(dim('  Run \'via status\' to verify your setup.'));
    blank();
  }

  if (asJSON) console.log(JSON.stringify({ dir, tools, written, dry }, null, 2));
}

